### ISSUE TITLE
Cannot set extension to "tag.html"

### ISSUE THREAD

**Issue by ShiMeiWo** [riot/rollup-plugin-riot#106]
I used to use extension ".tag.html" by plugin-settings to make Riot tag files, but at v4, rollup shows error that "Unexpected token (Note that you need plugins to import files that are not JavaScript)". It goes well when I change the extension into "html".

* reproduce
https://glitch.com/edit/#!/flat-olive

`riot.config.js`
```
export default {
  hot: false,
  extension: 'tag.html'
}
```

`rollup.config.js`
```
import riot  from 'rollup-plugin-riot'
...
plugins: [
    riot({
      ext: 'tag.html'
    }),
]
```

Thanks.

**Comment by GianlucaGuarini** [comment]
For now you can use `tag-html` or `riot`. At moment  we don't support different dot extensions at same time like `foo.tag.html`

**Comment by ShiMeiWo** [comment]
Thank you for your answer. I will try `foo.riot`.
