### ISSUE TITLE
Typescript as Preprocessor

### ISSUE THREAD

**Issue by coreequip** [riot/rollup-plugin-riot#117]
Hi Gianluca,

thanks for your great work!

Is there any example how to use Typescript in RIOT components? 

My approach so far:

rollup.config.js
```js
...
import {registerPreprocessor} from '@riotjs/compiler'
import * as ts from 'typescript'
...
registerPreprocessor('javascript', 'ts', function (code, {options}) {
    const {file} = options

    const result = ts.transpileModule(code, { // doesnt find "transpileModule"
        fileName: file,
        compilerOptions: {
            module: ts.ModuleKind.ESNext
        }
    })

    return {
        code: result.outputText,
        map: null
    }
})
...
plugins: [
...
    riot(),
...
]
```

`src/components/test.riot`
```html
<test>
    <script type="ts">
        const a :number = 123
    ...
```

Yes, I found this [rollup config file](https://github.com/gaconkzk/fliesml/blob/master/rollup.config.js) but it doesn't show how to render TypeScript. My approach fails on the use of the TypeScript library. May I have a small hint on that?

Cheers.

**Comment by GianlucaGuarini** [comment]
I don't see any problem with your code. Could you please create a demo repository with some simple files to reproduce it? thanks

**Comment by coreequip** [comment]
Thanks for checking. I will and comment here.

**Comment by coreequip** [comment]
@GianlucaGuarini After setting up a clean project to the the problem it turned out that everything works as you mentioned. 👍 

I don't want to open a new ticket but I found another issue about this plugin: `rollup-plugin-riot@4.0.2`

`rollup-plugin-riot` depends on `@riotjs/compiler@"^4.8.2"` so there is a problem resolving the dependency tree. "The rest" dependes on compiler `5.0.0`

Should I dump this in a new ticket?
