### ISSUE TITLE
README should reflect current Rollup config format

### ISSUE THREAD

**Issue by bradisbell** [riot/rollup-plugin-riot#118]
The config example using `entry` and what not threw me for a bit of a loop for a minute.  I think this config format was for an older version of Rollup?  It would be helpful to use the current version, with `input` and `output`.

**Comment by GianlucaGuarini** [comment]
@bradisbell thank you for your feedback. Would you be interested in making a PR? That would help closing this issue.

**Comment by bradisbell** [comment]
Will do!
