### ISSUE TITLE
Cannot generate a sourcemap if non-sourcemap-generating transformers are used

### ISSUE THREAD

**Issue by cbetta** [riot/rollup-plugin-riot#3]
I'm getting the following error when trying to compile and generate a sourcemap:

```
Cannot generate a sourcemap if non-sourcemap-generating transformers are used
```

Is there a way to make sourceMaps work with this?

**Comment by cognitom** [comment]
Hi @cbetta, at this point riot-compiler doesn't generate the sourcemap.

We could add an empty sourcemap like this:
https://github.com/TrySound/rollup-plugin-string/blob/master/src/index.js#L16
to here:
https://github.com/riot/rollup-plugin-riot/blob/master/src/index.js#L27

**Comment by cbetta** [comment]
Hmmm, what would that do?

**Comment by jsannerstedt** [comment]
Any plans for this?

**Comment by cognitom** [comment]
@jsannerstedt I'm waiting the progress of `riot-compiler`.
https://github.com/riot/compiler/issues/56

**Comment by joelchucn** [comment]
https://github.com/riot/compiler/issues/56 

It seems that riot 3 compiler support source map. Any plan to include this to this rollup plugin?

**Comment by cognitom** [comment]
@joelchucn the issue hasn't been resolved yet.
AFAIK, there's no API to do that, at this point.
https://github.com/riot/compiler/tree/master/doc#on-server

**Comment by GianlucaGuarini** [comment]
yes the source map in https://github.com/riot/compiler/issues/56 is generate by webpack. The compiler gives us the possibility to output the path to the original source file via the `{ debug: true }` option though

**Comment by GianlucaGuarini** [comment]
the new version 1.2.0 will generate sourcemaps properly enjoy it ✌️
