### ISSUE TITLE
Good bye, Babel

### ISSUE THREAD

**Issue by cognitom** [riot/rollup-plugin-riot#33]
To fix the test on Travis, I've removed the dependencies related to Babel. Maybe we could fix them, but bit time-consuming. Instead of that, here're some changes made:

- Ava to Mocha a451b126d1e9dab66962eacae30b6609ae9e1148
- Babel to Bublé 0617ab9ad7d279290f0bedc6fa5dc5169d436b6e

[Bublé](https://buble.surge.sh/) is much simpler alternative of Babel. For simple modules like `rollup-plugin-riot`, it's enough and faster option.

**Comment by GianlucaGuarini** [comment]
@cognitom yes go for it bravo!
