### ISSUE TITLE
Failed to parse a tag if inline styling were used

### ISSUE THREAD

**Issue by bmikeb** [riot/rollup-plugin-riot#88]
Hello,

My app uses a tag
`<my-tag style="height:{height}px"> <my-tag>`
Riot compiler makes its work fine, while rollup plugin fires an error. If instead of inline styling I'm using a `class={myclass:condition}` notation, all worked fine though.

Mikhail

**Comment by cognitom** [comment]
@bmikeb could you show us your `rollup.config.js`?

**Comment by bmikeb** [comment]
Hi there,

See attached

Mikhail

**Comment by cognitom** [comment]
@bmikeb I can't see anything...

**Comment by bmikeb** [comment]
Maybe mail app rejected js attached
check the link below

https://www.dropbox.com/s/9rxwe5fwml64dn2/Archive.zip?dl=0

**Comment by cognitom** [comment]
I don't like to download and open a zip file...
Why not just paste your code on this thread?
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by bmikeb** [comment]
`import riot from 'rollup-plugin-riot'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import buble from 'rollup-plugin-buble'
import postcss from 'postcss'
import postcssCssnext from 'postcss-cssnext'

export default {
  entry: 'tags/main.js',
  dest: 'dist/bundle.js',
  plugins: [
    riot({
      style: 'cssnext',
      parsers: {
        css: { cssnext }
      }
    }),
    nodeResolve({ jsnext: true }),
    commonjs(),
    buble()
  ],
  format: 'iife'
}

/**
 * Transforms new CSS specs into more compatible CSS
 */
function cssnext (tagName, css) {
  // A small hack: it passes :scope as :root to PostCSS.
  // This make it easy to use css variables inside tags.
  css = css.replace(/:scope/g, ':root')
  css = postcss([postcssCssnext]).process(css).css
  css = css.replace(/:root/g, ':scope')
  return css
}'

**Comment by bmikeb** [comment]
`import riot from 'rollup-plugin-riot'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import buble from 'rollup-plugin-buble'
import postcss from 'postcss'
import postcssCssnext from 'postcss-cssnext'

export default {
  entry: 'tags/main.js',
  dest: 'dist/bundle.js',
  plugins: [
    riot({
      style: 'cssnext',
      parsers: {
        css: { cssnext }
      }
    }),
    nodeResolve({ jsnext: true }),
    commonjs(),
    buble()
  ],
  format: 'iife'
}

/**
 * Transforms new CSS specs into more compatible CSS
 */
function cssnext (tagName, css) {
  // A small hack: it passes :scope as :root to PostCSS.
  // This make it easy to use css variables inside tags.
  css = css.replace(/:scope/g, ':root')
  css = postcss([postcssCssnext]).process(css).css
  css = css.replace(/:root/g, ':scope')
  return css
}`

**Comment by bmikeb** [comment]
Sorry, it seems markdown failed to format the code

**Comment by bmikeb** [comment]
```
"devDependencies": {
    "browser-sync": "^2.18.6",
    "chokidar-cli": "^1.2.0",
    "postcss": "^5.2.9",
    "postcss-cssnext": "^2.9.0",
    "rollup": "^0.41.1",
    "rollup-plugin-buble": "^0.15.0",
    "rollup-plugin-commonjs": "^7.0.0",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-riot": "^1.1.0",
    "rollup-plugin-uglify": "^1.0.2"
  }```

**Comment by cognitom** [comment]
@bmikeb hmm..., I couldn't reproduce the issue you reported.
I tried [this example](https://github.com/riot/examples/tree/gh-pages/rollup) and changed slightly to use inline stylings. But it worked perfectly.

You may need to provide a whole example repository to reproduce the issue, I think.

**Comment by bmikeb** [comment]
Sorry, it was my bad. Really, all works fine.
Thank you.
