### ISSUE TITLE
UNRESOLVED_IMPORT for imported plugins

### ISSUE THREAD

**Issue by bmikeb** [riot/rollup-plugin-riot#89]
Hi,
trying to use riot.config.js (https://github.com/riot/examples/tree/gh-pages/riot-config), steps done, but on```npm run build``` console fires an error:
```
{ code: 'UNRESOLVED_IMPORT',
  message: '\'buble\' is imported by riot.config.js, but could not be resolved – treating it as an external dependency',
  toString: [Function] }
...
```
Plz advise.

**Comment by GianlucaGuarini** [comment]
please reopen it here it seems to be an issue related to the riot compiler + rollup https://github.com/riot/examples/tree/gh-pages/riot-config

**Comment by bmikeb** [comment]
I'm sorry, I noticed that no file was changed in the link
