### ISSUE TITLE
Sourcemap is likely to be incorrect

### ISSUE THREAD

**Issue by riccardoscalco** [riot/rollup-plugin-riot#92]
Using the plugin without options (`riot()`), I have the following warning from rollup:
```
Sourcemap is likely to be incorrect: a plugin was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
https://github.com/rollup/rollup/wiki/Troubleshooting#sourcemap-is-likely-to-be-incorrect
```

Any help? Thanks.

**Comment by StarpTech** [comment]
I have the same issue

**Comment by justintaddei** [comment]
Same here. Anyone figure out a solution or workaround yet?

**Comment by StarpTech** [comment]
As far I know source maps aren't supported by the compiler its planned for 4.0

**Comment by StarpTech** [comment]
Any news?

**Comment by GianlucaGuarini** [comment]
@StarpTech any help? https://github.com/riot/compiler/issues/56  :)

**Comment by StarpTech** [comment]
I will always trying to help if you can give me some hints. Awesome to see that experimental source map is there.
